### ISSUE TITLE
Roadmap: gammodels package

### ISSUE THREAD

**Issue by mdancho84** [business-science/gamsnip#1]
# Modelgam Project Roadmap - MVP
- [X] Create Package Structure
- [ ] Develop MVP Algorithms (#2) - Get basic use-cases from business-science/modeltime#71, Test on several datasets 
- [ ] Develop R
    - [x] Top Priority - `gen_additive_mod()` algorithm with `gam` engine (#2)
    - [x] Fix Workflow Issue (#3)
    - [ ] Add classification / logistic regression - role = "classification"
    - [ ] Determine if any parameters needed for `gen_additive_mod()`
- [ ] Create Tests (#4)
- [x] Automate Tests with GitHub Actions ()
- [ ] Make AWESOME README ()
- [ ] Add Vignettes - Getting Started (#5)
- [ ] Make Hex Logo ()
- [x] Add Pkgdown Documentation ()
- [ ] Finalize DESCRIPTION - Update authors
- [ ] Send to CRAN

# Future Backends

We can use caret as a baseline for adding more backends (engines) http://topepo.github.io/caret/train-models-by-tag.html#generalized-additive-model

- [ ] bam
- [ ] gamm
- [ ] mboost / boosted gams https://github.com/boost-R

# Recipes GAM Steps

Evaluate the feasibility of using a `recipe` interface for applying smoothing functions. Something like using `step_gam_smooth()` as a way of replacing `s()` inside a formula.

**Comment by mdancho84** [comment]
# Future Backends

We can use caret as a baseline for adding more backends (engines) http://topepo.github.io/caret/train-models-by-tag.html#generalized-additive-model

**Comment by BenWynne-Morris** [comment]
https://github.com/topepo/caret/blob/master/models/files/gam.R

**Comment by AlbertoAlmuinha** [comment]
Hi @BenWynne-Morris ,

Please, subscribe to #2 , I have written you a message there.

Regards
